---
# tasks file for monero-role

- name: install deps to build monero from source
  apt:
    name: "{{ item }}"
    state: present
  with_items: "{{ monero_source_deps }}"
  tags:
    - monero
    - build

- name: create monero group
  group:
    name: "{{ monero_group }}"
    state: present
  tags:
    - monero
    - build
    - setup

- name: create monero user
  user:
    name: "{{ monero_user }}"
    group: "{{ monero_group }}"
    system: true
    shell: /usr/sbin/nologin
    state: present
  tags:
    - monero
    - build
    - setup

- name: create installation directory
  file:
    path: "{{ monero_install_dir }}"
    owner: root
    group: root
    mode: 0775
    state: directory
  tags:
    - monero
    - build
    - install

- name: create nix dir structure
  file:
    path: "{{ monero_install_dir }}{{ item }}"
    owner: root
    group: root
    mode: 0775
    state: directory
  with_items:
    - /src
    - /bin
    - /etc
    - /var
    - /var/lib
  tags:
    - monero
    - build
    - install

- name: create monero data dirs
  file:
    path: "{{ monero_install_dir }}{{ item }}"
    owner: "{{ monero_user }}"
    group: "{{ monero_group }}"
    mode: 0775
    state: directory
  with_items:
    - /var/lib/monero
    - /var/log
  tags:
   - monero
   - build
   - install

- name: download monero source code
  git:
    repo: "{{ monero_git }}"
    version: "{{ monero_version }}"
    dest: "{{ monero_install_dir }}/src/{{ monero_version }}"
    update: no
  register: monero_code
  tags:
    - monero
    - build

- name: make monero
  make:
    chdir: "{{ monero_install_dir }}/src/{{ monero_version }}"
  when: monero_code.changed
  tags:
    - monero
    - build

- name: install monero binaries
  shell: "/bin/cp -p {{ monero_install_dir }}/src/{{ monero_version }}/build/release/bin/{{ item }} {{ monero_install_dir }}/bin/"
  args:
    creates: "{{ monero_install_dir }}/bin/{{ item }}"
  with_items: "{{ monero_binaries }}"

- name: configure logrotate for httpd
  template:
    src: logrotate.j2
    dest: /etc/logrotate.d/monero
    owner: root
    group: root
    mode: 0644
  tags:
    - monero
    - logrotate
    - config
