---
# handlers file for monero-role

#  this won't work unti ansible 2.4
#- name: reload systemd
#  systemd:
#    daemon_reload: yes

- name: reload systemd
  command: systemctl daemon-reload

- name: restart monerod
  systemd:
    name: monerod
    state: restarted

- name: reload ufw
  ufw:
    state: reloaded
 